### ISSUE TITLE
'.csv' gets converted to '.csv.xls'

### ISSUE THREAD

**Issue by derdilla** [AymanYassinn/JSaver#1]
When saving a file with a csv extension JSaver magically adds a '.xls'. This only happens with the lower case '.csv'.

After setting the default directory the issue occurres when saving files the following way:
```dart
String path = await FileSaver.instance.saveFile(name: 'file', ext: 'csv', bytes: fileContents);
print(path); // /storage/emulated/0/Android/data/com.derdilla.bloodPressureApp/files/file.csv
JSaver.instance.save(
  fromPath: path,
  androidPathOptions: AndroidPathOptions(toDefaultDirectory: true)
);
```

You can see that the 3rd party [`FileSaver`](https://pub.dev/packages/file_saver) is saving the files correctly.
The issue occurred on an emulated android 13 phone.

**Comment by AymanYassinn** [comment]
This Issue was solved in current version 1.3.0
